### ISSUE TITLE
CI: fix ruby 2.7 build

### ISSUE THREAD

**Issue by mberlanda** [jamis/bulk_insert#59]
Make sure that ruby 2.7 builds can run.
Currently there is a minor issue with bundler installation in travis:

```
The command "eval bundle install --jobs=3 --retry=3 --deployment " failed. Retrying, 2 of 3.

Traceback (most recent call last):

	4: from /home/travis/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `<main>'

	3: from /home/travis/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `eval'

	2: from /home/travis/.rvm/gems/ruby-2.7.1/bin/bundle:23:in `<main>'

	1: from /home/travis/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'

/home/travis/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.2) required by your /home/travis/build/jamis/bulk_insert/Gemfile.lock. (Gem::GemNotFoundException)

To update to the latest version installed on your system, run `bundle update --bundler`.

To install the missing version, run `gem install bundler:1.17.2`
```

<https://travis-ci.com/github/jamis/bulk_insert/jobs/337238175>

**Comment by mberlanda** [comment]
Fixed in #61
